### ISSUE TITLE
authorize() return value

### ISSUE THREAD

**Issue by RSSchermer** [simplabs/ember-simple-auth#903] opened 2016-02-18 21:07 UTC
I find myself using `authorize()` in a model hook. However, I'm having to resort to a bit of ugliness to achieve this, initializing a variable in the outer scope and then setting it in the inner scope:

```js
model() {
  let model;

  this.get('session').authorize('authorizer:oauth2', (headerName, headerValue) => {
    const headers = {};
    headers[headerName] = headerValue;
    const url = ...;

    model = Ember.$.ajax(url, { headers: headers }).then((data) => {
      return this.store.push(data);
    });
  });

  return model;
}
```

If the `authorize()` were to return its block's return value (or `null` if the user is not authenticated) then this could be changed to:

```js
model() {
  return this.get('session').authorize('authorizer:oauth2', (headerName, headerValue) => {
    const headers = {};
    headers[headerName] = headerValue;
    const url = ...;

    return Ember.$.ajax(url, { headers: headers }).then((data) => {
      return this.store.push(data);
    });
  });
}
```

If giving `authorize()` its block's return value indeed seems sensible, I'd be happy to make PR.

**Comment by marcoow** [comment] 2016-02-19 08:15
Yeah, that's a good point. Actually the authorization API is a bit unfortunate in general in its current state. This also relates to #870 (see discussion there) - would be cool to get some more input there.

**Comment by RSSchermer** [comment] 2016-02-19 09:42
Ok - WARNING - here's a bit of a braindump:

There's a bit of a disconnect between how I was expecting this API to work and how it actually works. Here's what I was expecting (simply based on the method name) in pseudocode:

```js
const request = new Request(...);

const authorizedRequest = this.get('session').authorize('authorizer:oauth2', request);

const resultPromise = runRequest(authorizedRequest);
```

Here `authorize()` modifies a request so that it is now an authorized request. The upside of this approach is that this is very powerful; you can modify a request in arbitrary ways and the user does not have to do any additional work. The obvious downside is that you expect a standardized request object. Unfortunately, this is not standardized at all in javascript. The closest thing in an Ember context though would probably be [the jquery ajax settings object](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings). In actual Ember code this might then look something like this:

```js
const request = {
  url: 'http://example.com/api/things',
  dataType: 'json',
  headers: {
    'my-custom-header': 'some-value'
  }
};

const authorizedRequest = this.get('session').authorize('authorizer:oauth2', request);

const resultPromise = Ember.$.ajax(authorizedRequest);
```

The downside then is of course that it is now at least to a certain extend tied to jquery ajax.

There's an alternative option that seems more in line with what `authorize()` actual current purpose seems to be: to simply make the authorization headers available in the current scope. This would look something like this:

```js
const authorizationHeaders = this.get('session').buildAuthorizationHeaders('authorizer:oauth2');

const request = {
  url: 'http://example.com/api/things',
  dataType: 'json',
  headers: Ember.merge({
    'my-custom-header': 'some-value'
  }, authorizationHeaders)
}

const resultPromise = Ember.$.ajax(request);
```

The upside to this approach is that it is more flexible: it is not as tightly coupled with jquery ajax. The downside is that it is less powerful. You can only do header based authorization. For example, adding query params would not be possible with this approach, whereas this would probably be perfectly doable in the first approach. Also, the user may have to do more work (merge the headers into his own).

So I think it's a flexibility vs power trade-off. I probably have a slight preference for the first approach, as I think jquery ajax is pretty much what is exclusively used in the Ember ecosystem and it intuitively feels like a nicer API.

**Comment by marcoow** [comment] 2016-02-19 09:52
See the discussion in #870 - the idea would be to keep the current level of flexibility where `authorize` could authorize anything really (as it only turns the session data into authorization info of some kind) but also allow to pass additional options as e.g. the request object (which is needed e.g. when including hashes that include the request URL).

The question is how that can be done in a backwards compatible way which would probably work somehow when making `authorize` return a promise which would also solve your original problem.

Regarding: jQuery AJAX: I don't really want to couple authorizers to that as the jQuery dependency is probably being dropped from Ember soon and e.g. the new `fetch` API is already on the horizon with polyfills being available already. Also I don't think a use case where someone authorizes a call to an external API and not a request is too exotic.

**Comment by RSSchermer** [comment] 2016-02-19 10:25
I wasn't aware of the new fetch api. You were referring to [this](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [this](https://gist.github.com/tomdale/203ea125acd0be8b5f1f)? This is actually the exact bit of standardization I mentioned javascript was missing. I think this might actually make the first, more powerful approach more interesting.

It also occurred to me that session might perfectly well implement both `authorize()` (or perhaps a better name is `authorizeRequest()`) and `buildAuthorizationHeaders()` as I attempted to outline above (although then with [a fetch request](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_your_own_request_object) or [fetch init options](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_request_options) rather than a jquery ajax settings object). This would perhaps give you the best of both worlds.

However, I do understand not wanting to break BC.

**Comment by marcoow** [comment] 2016-02-19 10:47
The point is that the session shouldn't really care about what is being authorized (a request or a method call or whatever) - only the authorizer actually is bound to a specific authorization target as it e.g. generates request headers.

I think when there eventually would be a standardized networking service it would make sense to add a dedicated method to the session to authorize that but until then I don't see how that would work as people use different request mechanisms and would have different requirements for such a method which would only lead ESA to end up with multiple methods for authorizing requests in order to support every individual case.

**Comment by RSSchermer** [comment] 2016-02-19 11:38
> The point is that the session shouldn't really care about what is being authorized (a request or a method call or whatever) - only the authorizer actually is bound to a specific authorization target as it e.g. generates request headers.

I completely agree that flexibility is an important goal.

I however think that using a callback to achieve what `authorize()` is currently doing (generating request headers and making them available to a scope) is perhaps a little odd and using a factory method (such as `buildAuthorizationheaders()` or perhaps `createAuthorizationHeaders()`) seems much more flexible and intuitive for this purpose. With regards to #870, this factory method could take an options object as an optional second argument. If I understand #870 correctly, this would address the underlying issue there. The obvious downside is of course still that it breaks BC (although you could keep `authorize()` in place for a while with a deprecation notice).

> I think when there eventually would be a standardized networking service it would make sense to add a dedicated method to the session to authorize that but until then I don't see how that would work as people use different request mechanisms and would have different requirements for such a method which would only lead ESA to end up with multiple methods for authorizing requests in order to support every individual case.

Now that I learned of the new fetch API, I would definitely not propose something like `authorizeRequest()` be added before Ember standardizes around the fetch API. In my previous post I was merely noting that when it does, this might be an attractive way of implementing authorization logic.

I agree that ending up with multiple methods for different library specific request types would be very bad. However, with fetch Requests apparently becoming a new browser standard, rather than just another library, I don't think there is much risk of that; fetch Requests are clearly special in that regard.

**Comment by marcoow** [comment] 2016-02-19 11:46
> I however think that using a callback to achieve what authorize() is currently doing (generating request headers and making them available to a scope) is perhaps a little odd and using a factory method (such as buildAuthorizationheaders() or perhaps createAuthorizationHeaders()) seems much more flexible and intuitive for this purpose.

The point is just that the method might not actually return headers but maybe only a string, maybe a hash with all kinds of data - that completely depends on the authorizer being used.

> I agree that ending up with multiple methods for different library specific request types would be very bad. However, with fetch Requests apparently becoming a new browser standard, rather than just another library, I don't think there is much risk of that; fetch Requests are clearly special in that regard.

I'd wait until it becomes clearer which API settles on before deciding on a way to go here. In the end the solution would have to target Ember's request service API, not the `fetch` API directly.

Another thing to consider might be that it could make sense to while changing the authorization API already, make it promise based so that it returns a promise that resolves when authorization is successful and rejects otherwise. That would also solve a hard to find error case being caused by the fact that the callback is never called when the session is not currently authenticated, potentially leading to a situation where a promise never resolves or rejects, effectively halting the application.

**Comment by RSSchermer** [comment] 2016-02-19 13:04
> The point is just that the method might not actually return headers but maybe only a string, maybe a hash with all kinds of data - that completely depends on the authorizer being used.

I agree that this would indeed be ideal. However, it does not seem that this would work with the current [adapter mixin implementation](https://github.com/simplabs/ember-simple-auth/blob/d70020c710e1f35560089ec482dba25f3027ffc9/addon/mixins/data-adapter-mixin.js#L78-L80). In fact, I don't think it is possible to pass non-standard data (whether with the callback method or a factory method) without needing a custom adapter for each non-standard authorizer (although perhaps I'm missing a trick here). A more powerful `authorizeRequest()` approach could definitely do this without needing custom adapters, although I think we now agree that this needs to wait until Ember data is based on the fetch API.

> I'd wait until it becomes clearer which API settles on before deciding on a way to go here. In the end the solution would have to target Ember's request service API, not the fetch API directly.

I think one of the nicer ways a fetch based Ember Data could allow you to authorize requests, is by allowing you to register Request transformers: Ember Data generates a fetch Request, it passes it through all registered Request transformers (which each take a Request as input and spit out a modified request) and then sends it off to the server.

> Another thing to consider might be that it could make sense to while changing the authorization API already, make it promise based so that it returns a promise that resolves when authorization is successful and rejects otherwise. That would also solve a hard to find error case being caused by the fact that the callback is never called when the session is not currently authenticated, potentially leading to a situation where a promise never resolves or rejects, effectively halting the application.

Are you referring to the current `authorize()` method? I guess that depends on if `authorize()` needs to be asynchronous (does heavy processing or IO, e.g. make a separate server round trip before sending the actual request. That would be a lot of overhead though before each request, not sure if such a use case makes sense). If it doesn't need to be asynchronous, then I think the more idiomatic synchronous thing to do would be to just throw an exception if the session is not currently authenticated. If you were to ditch the callback approach in favor of a factory method I think this would become a non-issue; a factory method could just return an empty headers object `{}` (or `null` or `false`) if the session is not currently authenticated.

**Comment by marcoow** [comment] 2016-02-19 13:20
> Are you referring to the current authorize() method? I guess that depends on if authorize() needs to be asynchronous (does heavy processing or IO, e.g. make a separate server round trip before sending the actual request. That would be a lot of overhead though before each request, not sure if such a use case makes sense). If it doesn't need to be asynchronous, then I think the more idiomatic synchronous thing to do would be to just throw an exception if the session is not currently authenticated. If you were to ditch the callback approach in favor of a factory method I think this would become a non-issue; a factory method could just return an empty headers object {} (or null or false) if the session is not currently authenticated.

Yes, I'm referring to the current `authorize` method. Whether it needs to be async or nor actually depends on the authorizer being used. The problem is that it currently does not support async authorization which might actually be a problem with some authorization mechanisms. The session stores were just made async for a similar reason.

Also like I said above, the current implementation makes it very easy to write code like this:

```js
return new Promise((resolve, reject) => {
  this.get('session').authorize('authorizer:oauth2', (headerName, headerValue) => {
    return Ember.$.ajax(….)then(resolve, reject);
  });
});
```

which causes big problems as when the session is not authenticated it would never call the callback and the returned promise would never resolve or reject, thus halting the complete application.

Also I'm not sure whether it would be great to throw an exception from `authorize` when the session is not authenticated as it would be more helpful to be able to use the method in a "when the session is authenticated run this, otherwise run that" way which would be easy if it returned a promise. Of course that could be done with passing a 2nd callback but that would be horrible API of course.

**Comment by RSSchermer** [comment] 2016-02-19 13:37
> Whether it needs to be async or nor actually depends on the authorizer being used.

I think that is probably the main thing that would settle it in favor of promises.

What would it look like though? Perhaps:

```js
this.get('session').authorize('authorizer:oauth2').then((headerName, headerValue) => {
  ...
}).catch(() => {
  ...
});
```

Note that this is in essence the factory method approach with the factory method returning a promise:

```js
this.get('session').buildAuthorizationHeaders('authorizer:oauth2').then((headerName, headerValue) => {
  ...
}).catch(() => {
  ...
});
```

Although in this case I think I do actually like `authorize` as the method name (I think it does fit and it is obviously much more terse).

**Comment by marcoow** [comment] 2016-02-19 13:40
Yes, it would look somewhat like that. The authorization method can never have a reference to "headers" or anything else relating to XHR in its name though as it depends on the authorizer what kind of auth info it generates (which might not be headers and maybe not even sth. that would be used to authorize a request).

A method specifically for XHRs might be added once Ember settles on a network request implementation as proposed in Tom's above mentioned proposal.

**Comment by RSSchermer** [comment] 2016-02-19 14:05
Something like:

```js
this.get('session').authorize('authorizer:oauth2').then((...) => {
  ...
}).catch(() => {
  ...
});
```

Where `authorize` optionally takes a second options argument, definitely seems good to me.

I still believe though that if different authorizers end up passing different things to that promise, it may be unavoidable that you'll need a different Ember Data adapter for each.

On a somewhat unrelated note (as long as were discussing breaking changes anyway), I think I might prefer that if headers are passed, they are passed as a headers object, rather than `headerName`, `headerValue`. I think this makes it easier to pass more than 1 header. I think it's also somewhat cleaner to handle than `headerName`, `headerValue`:

```js
this.get('session').authorize('authorizer:oauth2').then((headers) => {
  return Ember.$.ajax('someurl', { headers: headers });
});
```

vs

```js
this.get('session').authorize('authorizer:oauth2').then((headerName, headerValue) => {
  const headers = {};
  headers[headerName] = headerValue;
  
  return Ember.$.ajax('someurl', { headers: headers });
});
```

Or when merging with more custom headers:

```js
this.get('session').authorize('authorizer:oauth2').then((authHeaders) => {
  const headers = Ember.merge({
    'some-header': 'some-value'
  }, authHeaders);

  return Ember.$.ajax('someurl', { headers: headers });
});
```

vs

```js
this.get('session').authorize('authorizer:oauth2').then((headerName, headerValue) => {
  const headers = {
    'some-header': 'some-value'
  };
  headers[headerName] = headerValue;
  
  return Ember.$.ajax('someurl', { headers: headers });
});
```

**Comment by marcoow** [comment] 2016-02-19 14:16
> I still believe though that if different authorizers end up passing different things to that promise, it may be unavoidable that you'll need a different Ember Data adapter for each.

Actually the `DataAdapterMixin` only works with authorizers that generate headers. I think it's that way round and people needing other kinds of authorizers to work would have to override the respective methods.

> On a somewhat unrelated note (as long as were discussing breaking changes anyway), I think I might prefer that if headers are passed, they are passed as a headers object, rather than headerName, headerValue. I think this makes it easier to pass more than 1 header. I think it's also somewhat cleaner to handle than headerName, headerValue:

That's absolutely true and would also be a consequence of the promise based approach anyway as `resolve` only takes one argument anyway.

**Comment by RSSchermer** [comment] 2016-02-19 14:24
> Actually the DataAdapterMixin only works with authorizers that generate headers. I think it's that way round and people needing other kinds of authorizers to work would have to override the respective methods.

I think in the future that might be resolved by adding `authorizeRequest()`. If Ember Data becomes fetch based it should not need to use `authorize()` at all, it could exclusively use `authorizeRequest()` which, as mentioned, I think should be able to make arbitrary modifications to the request.

**Comment by marcoow** [comment] 2016-06-15 15:17
closing this as it won't be needed anymore once we have #979

**Closed by marcoow** 2016-06-15 15:17 UTC
Labels: triage
