### ISSUE TITLE
OAuth authenticator: retry token refresh if connection fails

### ISSUE THREAD

**Issue by rhyek** [simplabs/ember-simple-auth#980] opened 2016-05-16 07:56 UTC
There is an issue, currently, when a token refresh fails due to a connection error: no new attempts are made at a later time resulting in the current session becoming invalid until the user re-authenticates via a browser refresh, re-logging, or logging in using a different tab.

Consider the case where a user is filling out a long form. A token refresh is scheduled to happen soon and they lose connectivity momentarily. The token refresh request is sent out and fails unbeknownst to the user. Connectivity is regained, the user finishes their work, hits the send button, and they get an unauthorized error from the server repeatedly even after several attempts.

What is the best approach for preventing this problem when you might expect users to sometimes work with unstable connections?

A solution might be for the developer to be constantly saving application state in local storage and force a session invalidation when a network error occurs. The user logs back in when possible and their work is still there. This might be the best solution depending on the use-case.

A simpler solution (or one in addition to the previous) might be to just schedule a new token refresh attempt every x seconds until successful. Say, every 10 seconds. I have extended my own authenticator with a small change that does this:

```
import Ember from 'ember';
import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';
const { isEmpty, RSVP, run, assign } = Ember;

export default OAuth2PasswordGrant.extend({
    _refreshAccessToken(expiresIn, refreshToken) {
        const data                = { 'grant_type': 'refresh_token', 'refresh_token': refreshToken };
        const serverTokenEndpoint = this.get('serverTokenEndpoint');
        return new RSVP.Promise((resolve, reject) => {
            this.makeRequest(serverTokenEndpoint, data).then((response) => {
                run(() => {
                    expiresIn       = response['expires_in'] || expiresIn;
                    refreshToken    = response['refresh_token'] || refreshToken;
                    const expiresAt = this._absolutizeExpirationTime(expiresIn);
                    const data      = assign(response, { 'expires_in': expiresIn, 'expires_at': expiresAt, 'refresh_token': refreshToken });
                    this._scheduleAccessTokenRefresh(expiresIn, null, refreshToken);
                    this.trigger('sessionDataUpdated', data);
                    resolve(data);
                });
            }, (xhr, status, error) => {
                Ember.Logger.warn(`Access token could not be refreshed - server responded with ${error}.`);

                // new
                if (xhr.status === 0) {
                    let delay = 10;
                    Ember.Logger.warn(`Refresh token failed due to a connection error. Retrying in ${delay} seconds.`);
                    this._scheduleAccessTokenRefresh(expiresIn, new Date().getTime() + delay * 1000, refreshToken);
                }
                // end new

                reject();
            });
        });
    }
});
```

Any downsides to this? Is there a better solution? I'm also waiting for #840 which I think would help my case.

**Comment by marcoow** [comment] 2016-05-16 11:01
> A simpler solution (or one in addition to the previous) might be to just schedule a new token refresh attempt every x seconds until successful. Say, every 10 seconds.

I'm not sure that's a great idea, especially not adding that to the OAuth 2.0 authenticator's implementation. As far as the authenticator is concerned, a failed refresh request just doesn't refresh the token - regardless of whether it failed because of the refresh token being invalid or the network being unavailable. I'd say refreshing the token when the network becomes available again is an application concern (using the authenticator of course). By handling that in the application (e.g. some code in the application route or so that observes the network availability) we can keep a lot of complexity out of authenticators.

I'd rather do sth. like this:

```js
// app/routes/application.js
import Ember from 'ember';

const { inject: { service } } = Ember;

export default Ember.Route.extend({
  session: service(),

  _networkBecomesAvailable() {
    if (this.get('session.isAuthenticated')) {
      let authenticator = this.get('session.authenticator');
     authenticator._refreshAccessToken(); 
    }
  }
});
```

Of course currently the authenticator's `_refreshAccessToken` is private but we were recently discussing potentially making more of the authenticator API publicly available. I guess in the case of `_refreshAccessToken` we could probably just do that but we'd have to look at the implications in more detail.

**Comment by rhyek** [comment] 2016-05-16 11:36
The problem I see with that is then the application would need to be aware of the access token's lifetime, possibly the authenticator's token refresh schedule, and when a refresh token request has failed. Not possible at this time. Currently, you'd need to have a recurring task constantly refreshing the token when there is no need to.

I suppose the authenticator could trigger a `refreshTokenFailed` event with the `xhr` as an argument and then the application would listen to it and handle the error accordingly. That would actually be great.

**Comment by rhyek** [comment] 2016-05-16 11:56
So I just attempted this, but realized `this.get('session.authenticator')` isn't actually a thing, apparently. I could try and get this working and make a PR, but I'd have to expose the authenticator via the session and I'm not sure this is something you'd want right now?

**Comment by marcoow** [comment] 2016-05-16 11:59
Let's maybe move this discussion to #dev-simple-auth in the Ember Community Slack. As I said we were discussing opening up the authenticator's API publicly a few weeks ago already.

**Comment by ErisDS** [comment] 2016-05-20 09:28
I've just read this issue and realised (after nearly 2 years) that this is probably the reason why Ghost's CEO constantly suffers session loss when using Ghost. He lives in Egypt, where the internet connectivity is pretty poor.

Personally, I can use Ghost endlessly without any issue, meanwhile he reports getting logged out constantly. Until now, we didn't have any working theories for why a handful of people seemed to have session issues that weren't reproducible. After all, we can easily simulate slow connections, but it's not yet a common thing to simulate intermittent connections.

I understand why it's being proposed that this is an application-level issue, and I'm more than happy to have the fix go into Ghost rather than ESA, but I just wanted to convey that this has been a point of contention for us - an issue we hadn't known how to solve - for a really long time. 

If it isn't something that's going to be solved at the authenticator level, I'd recommend adding serious documentation about the fact that connection loss can cause this issue and how to solve it.

Of course, this comment is predicated on this being the cause of the problem, but it's the only working theory that makes any sense at all.

**Comment by rhyek** [comment] 2016-05-26 12:25
I have a created a [gist](https://gist.github.com/rhyek/55e75d6dc45eaa65bceac510196c2a30#file-application-js-L115) with my complete oauth2 authenticator in case it helps anyone. Features are:

- Ensure only one tab/window is handling token refreshes to avoid 400/401 errors due to concurrent requests and lowering bandwidth used.
- If a token refresh is rejected with 400/401 http status codes, invalidate the session.
- Attempt token refreshes when 90% of the access token's lifetime has transpired, leaving the remaining 10% as an opportunity to retry the refresh in case of connection failures.
- If a token refresh failes due to a connection error, keep trying every 5 seconds until the current access token's lifetime has expired, in which case, the session will be invalidated.

**Comment by marcoow** [comment] 2016-05-27 07:08
@ErisDS: thanks for sharing that! You should already be able to do sth. like this:

```js
// app/routes/application.js
import Ember from 'ember';

const { inject: { service } } = Ember;

export default Ember.Route.extend({
  session: service(),

  _networkBecomesAvailable() {
    if (this.get('session.isAuthenticated')) {
      let authenticator = this.get('session.authenticator');
     authenticator._refreshAccessToken(); 
    }
  }
});
```

The plan would be to somehow make the `authenticator._refreshAccessToken();` part public API but I don't think the general approach would change much. Would be good to hear whether that approach solves the problem for Ghost at all.

**Comment by vkandy** [comment] 2016-07-16 19:24
> As far as the authenticator is concerned, a failed refresh request just doesn't refresh the token - regardless of whether it failed because of the refresh token being invalid or the network being unavailable.

@marcoow Completely agree with that statement. Dealing with failures should be an application's responsibility. Having said that, if the authenticator can distinguish between the _type_ of errors and provide a hook to delegate error handling, it makes it easier application developers to handle failure scenarios. 

Consider any one of these for instance -- a) if `_refreshAccessToken` would `reject()` with a reason or an error type and it bubbles up the application code or b) accept an error handler function or c) if the authenticator would emit an event. 

Or, what's the recommended way to handle errors when attempting to refresh tokens?

**Comment by marcoow** [comment] 2016-07-18 08:23
@vkandy: I'd say it should be fine to make [this](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L344) reject with the error instead of nothing at all.

**Comment by marcoow** [comment] 2017-02-08 15:47
Closing this for now. The fix implemented by @vkandy in TryGhost/Ghost-Admin!131 looks good but I don't think belongs into ESA.

**Closed by marcoow** 2017-02-08 15:47 UTC
