### ISSUE TITLE
Ember Simple Auth: The automatic session initialization is deprecated on Ember 3.28.4

### ISSUE THREAD

**Issue by jdaviderb** [simplabs/ember-simple-auth#2351] opened 2021-12-10 00:58 UTC
Ember simple auth version "^4.1.1" it's sending this warning on Ember 3.28.4

# How to replicate the problem?

1) ember new app-test
2) cd app-test
3) ember install ember-simple-auth
4) add this code on "application" route

```js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class Application extends Route {
  @service session;

  async beforeModel() {
    await this.session.setup();
  }
}

``` 

![image](https://user-images.githubusercontent.com/4649902/145499057-e33e461e-a8f7-4555-ba9b-676a52d43520.png)

# you can replicate the problem on this repo
https://github.com/jdaviderb/ember-simple-auth-deprecated-session-initialization-

**Comment by BobrImperator** [comment] 2021-12-10 07:56
Hi, thanks for reporting this as well as the reproduction ❤️ 

This feature currently is optional since 4.1.0 and requires additional configuration inside `ember-cli-build.js` file in order to get rid of the deprecation.
Later on we plan to make it the default behaviour.

Here's the documentation for this:
https://github.com/simplabs/ember-simple-auth/blob/master/guides/upgrade-to-v4.md

**Comment by Thenkei** [comment] 2021-12-10 10:19
Hello @BobrImperator,

> This feature currently is optional since 4.1.0 and requires additional configuration inside ember-cli-build.js file in order to get rid of the deprecation.

I might be wrong but this config is not loaded for now.. I think you missed the load function that should override the `useSessionSetupMethod` value.

https://github.com/simplabs/ember-simple-auth/blob/76410f1733013083b0bd20d92528985d793c07c2/packages/ember-simple-auth/addon/configuration.js#L53-L58

When it should be
```
  load(config) {
    this.rootURL = config.rootURL !== undefined ? config.rootURL : DEFAULTS.rootURL;
    this.routeAfterAuthentication =
      config.routeAfterAuthentication !== undefined
        ? config.routeAfterAuthentication
        : DEFAULTS.routeAfterAuthentication;
    // Here is the missing line
    this.useSessionSetupMethod = config.useSessionSetupMethod;
  },
```

**Comment by BobrImperator** [comment] 2021-12-10 10:24
@Thenkei If it's not working then it's a bug.

But notice that `useSessionSetupMethod` is imported from a file that's created during build time.
The `load` function on the other hand is for loading environment configs.

**Comment by Thenkei** [comment] 2021-12-10 10:33
> But notice that useSessionSetupMethod is imported from a file that's created during build time - this was the only way to expose build time variable to runtime that we could think of.

It make sense (at first glance I didn't get the 'ember-simple-auth/use-session-setup-method' import). It's weird in this case I should have an issue in my build process I will try to dig.
In the other hand, I tried my change (on the load function) and it works. 🤔

**Comment by BobrImperator** [comment] 2021-12-10 10:38
@Thenkei maybe you included the `useSessionSetupMethod` in your `environment.js` instead of `ember-cli-build.js`?
This is the only reason I can think of and it'd explain why adding the code to the `load` function works for you.

**Comment by Thenkei** [comment] 2021-12-10 10:51
@BobrImperator you're totally right.

> Inside your ember-cli-build.js you'll need to add useSessionSetupMethod flag and set it to true:

I missed that one. Why don't you let both way to configure the addon ? I found this quite confusing since the rest of the config is done in the `environment.js`.

Anyway, thanks for your time. 🙏

**Comment by BobrImperator** [comment] 2021-12-10 11:06
@Thenkei Glad it worked out 🚀 

> Why don't you let both way to configure the addon ?
The reason for this is that `useSessionSetupMethod` will funnel out `ApplicationRoute` when set to true and there's no easy way to read environment configuration from within ember-cli-build.
We also need to funnel it out because otherwise it causes issues for typescript users as well as embroider.

Hopefully I cleared out the question for you.
The PR and linked issues might also be able to answer this https://github.com/simplabs/ember-simple-auth/pull/2318

**Comment by Thenkei** [comment] 2021-12-10 11:33
Thanks for this really clear answer. I got it now. 🙏

**Comment by BobrImperator** [comment] 2022-01-04 08:46
I'm closing this since it looks like the issue has been resolved.
Feel free to re-open in case it's not resolved.

**Closed by BobrImperator** 2022-01-04 08:46 UTC
