### ISSUE TITLE
App not getting to sessionAuthenticationSucceeded on initial load of app

### ISSUE THREAD

**Issue by peyterkim** [simplabs/ember-simple-auth#416] opened 2015-01-30 14:45 UTC
Something strange is going on where when I first load the app, sign in, it does not hit the sessionAuthenticationSucceeded method in my ApplicationRoute. It should take me to a route called `/users/home` but its not reaching the transition. Now if I manually enter the url in the browser `/users/home`, log out, and log back in, the transition works.

Anyone have any idea why this is happening?

**Comment by marcoow** [comment] 2015-01-30 15:11
The `sessionAuthenticationSucceeded` event is only triggered when the session goes from unauthenticated to authenticated **after** the app has started. When the app already starts with an authenticated session, the event is not triggered.

**Comment by peyterkim** [comment] 2015-01-30 15:15
The app doesn't have an authenticated session when it's started, so it's going from unauthenticated to authenticated.

**Comment by marcoow** [comment] 2015-01-30 15:17
Hm, can you add some info to reproduce the problem?

**Comment by peyterkim** [comment] 2015-01-30 15:26
Authenticate method in authenticators/custom.js:
`  authenticate: function(credentials) {
  	return new Ember.RSVP.Promise(function (resolve, reject){
  		var loginPromise = Ember.$.post('/login', {'email':credentials.identification, 'password':credentials.password} );
  		loginPromise.then(function (data){
  			resolve({
  				token: data.user.api_key,
  				userData: data.user
  			});
  		}, function(error){
  			reject(error);
  		});
  	});
  }`

Application Route:
`var ApplicationRoute = Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    sessionAuthenticationSucceeded: function() {
      this.transitionTo('users.home');
    }
}
});`

Login Controller:
`import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';
export default Ember.ObjectController.extend(LoginControllerMixin, {
	authenticator: 'authenticator:custom',
	needs: ['application'],
	model: {}
});`

environment.js:
`ENV['simple-auth'] = { authenticationRoute: 'index', session: 'session:custom', routeAfterAuthentication: 'users.home'}`

Sorry, I don't know how to format blocks of code on github

**Comment by peyterkim** [comment] 2015-01-30 15:30
I feel like it's a pretty standard set up of simple-auth. Nothing out of the ordinary.

**Comment by peyterkim** [comment] 2015-02-02 16:14
Any word on this?

**Comment by bradplank** [comment] 2015-02-03 02:14
Are you using local storage?

```javascript
ENV['simple-auth'] = {
  store: 'simple-auth-session-store:local-storage'
}
```

If so, I have seen a similar issue with an iPhone 5 w/ iOS7 mobile safari.  That browser is not HTML5 compatible and causes a JavaScript exception to be thrown when `localStorage.setItem(this.key, data);` is called.

```javascript
try{
    localStorage.setItem("testKey","testValue)");
    // localStorage is supported
} catch (e){
    // private mode identified... - getting QUOTA_EXCEEDED_ERR: DOM Exception 22
    isHTML5Compatible = false;
}
```

If the browser does not support local storage, you may want to try using cookies instead.

```javascript
ENV['simple-auth'] = {
  store: 'simple-auth-session-store:cookie'
}
```

**Comment by ur5us** [comment] 2015-02-22 19:18
@marcoow What would be the best to make sure that a request made from an initializer fires after ESA (Devise) has setup the session? I've tried using `after: ["simple-auth", "simple-auth-devise"]` on the initializer but that doesn't work. As the `sessionAuthenticationSucceeded` event is not fired upon initial app start I can't use that as a hood either. Is there a proper way to do that?

**Comment by marcoow** [comment] 2015-02-22 19:32
@ur5us: When the session is authenticated on app startup, its `isAuthenticated` property should already be true after the `'simple-auth'` initializer has run and thus requests should already have the `Authorization` header after both the `'simple-auth'` and the `'simple-auth-devise'` initializer have run.

**Comment by ur5us** [comment] 2015-02-22 21:00
@marcoow I thought so too but it doesn't work for me. Probably I'm doing something wrong but using `after: ...` seems to be straight forward.

**Comment by marcoow** [comment] 2015-02-22 22:04
In your initializer the session should be authenticated if it was successfully restored from a persisted session. If it's not, please open a new issue.

**Comment by ur5us** [comment] 2015-02-27 00:35
@marcoow I'll try to isolate it. Also, it looks like it works for a production build of Ember but not when running dev mode.

**Comment by marcoow** [comment] 2015-03-05 09:32
@ur5us: any updates on this?

**Comment by knownasilya** [comment] 2015-03-26 16:06
@marcoow the reason is that `this.trigger('sessionAuthenticationSucceeded');` in setup triggers the event on the session, and not on the ApplicationRoute.

**Comment by knownasilya** [comment] 2015-03-26 17:22
Ah, my issue was that I had `beforeModel` defined on my `ApplicationRoute` and forgot to add `this._super(transition);`.

**Comment by marcoow** [comment] 2015-04-02 14:34
closing this, please reopen if there's still an issue.

**Closed by marcoow** 2015-04-02 14:34 UTC
Labels: question
