### ISSUE TITLE
Secure session cookie missing when restoring session in fastboot.

### ISSUE THREAD

**Issue by igorstajic** [simplabs/ember-simple-auth#1456] opened 2017-10-12 00:07 UTC
Fastboot request protocol is changed to to contain a colon (https://github.com/ember-fastboot/fastboot/pull/119/files). The change should be reflected here as well.

https://github.com/simplabs/ember-simple-auth/blob/e84ebdd93efce4148427ba982bc59676ac868ea2/addon/session-stores/cookie.js#L140

**Comment by marcoow** [comment] 2017-10-14 10:28
duplicate of simplabs/ember-cookies#131

**Closed by marcoow** 2017-10-14 10:28 UTC
