### ISSUE TITLE
[beginner] Assertion Failed: calling set on destroyed object

### ISSUE THREAD

**Issue by pierred69** [simplabs/ember-simple-auth#815] opened 2015-12-10 15:41 UTC
Hello,

I have the following error in my acceptance tests : "Assertion Failed: calling set on destroyed object". It doesn't occure everytime, and I don't have any idea about why it happens.

This one occures after a reject callback I call to test an authentication fail in my acceptance test.

Any idea ?

```javascript


import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from 'xxx/tests/helpers/start-app';

module('Acceptance | login', {
  beforeEach: function() {
    this.application = startApp();
  },

  afterEach: function() {
    Ember.run(this.application, 'destroy');
  }
});

```
```javascript

test('trying to connect with wrong ID / Password and fail', function(assert) {
  assert.expect(2);
  visit('/login');
  fillIn("input#input-email", "xxx@xxx.xxx");
  fillIn("input#input-password", "xxx");
  click("button#connect");
  andThen(function() {
    assert.equal(
      find("#error-input-email", ".popin-body").text().trim(), "Identifiants email et/ou mot de passe invalides"  // Mot de passe incorrect
    );
    assert.equal(
      find("#error-input-password", ".popin-body").text().trim(), "Identifiants email et/ou mot de passe invalides"  // Mot de passe incorrect
    );
  });
});

**Comment by marcoow** [comment] 2016-02-25 20:24
Is this still valid? Can you provide a stack trace if so? Otherwise close this please.

**Comment by marcoow** [comment] 2016-04-06 15:07
Closing this due to lack of feedback. Please reopen with more feedback if the problem persists.

**Closed by marcoow** 2016-04-06 15:07 UTC

**Comment by akatov** [comment] 2017-06-04 12:19
@marcoow, @pierred69  I have the same problem occurring intermittently. It looks like it's because the `sessionDataInvalidated` event is getting fired on the `Authenticator`, after the `InternalSession` is destroyed. The `InternalSession` which observes this event then calls `this._clear` which leads to
```js
    this.setProperties({
      isAuthenticated: false,
      authenticator:   null
    });
```
which leads to the above error.

I wasn't able to track down the exact sequence of events leading to this, as it happens only occasionally, and I suspect that the sequence of events may be different for me than it is for @pierred69 

However, a solution could be to add a `willDestroy` hook to `InternalSession` which removes all listeners from the authenticator.

**Comment by akatov** [comment] 2017-06-05 11:55
Actually, it may be better to remove the listeners on the destruction of the Authenticator object itself, so we could add a `willDestroy` hook to the `BaseAuthenticator`...

**Comment by marcoow** [comment] 2017-06-07 09:47
> However, a solution could be to add a willDestroy hook to InternalSession which removes all listeners from the authenticator.

This seems like a good addition. If you'd like to create a PR that would be awesome.

> Actually, it may be better to remove the listeners on the destruction of the Authenticator object itself, so we could add a willDestroy hook to the BaseAuthenticator...

The problem is that the `InternalSession` is destroyed when the authenticator's event is triggered so the initial suggestion was actually correct.

**Comment by zavan** [comment] 2021-01-15 18:54
I'm still bumping into this problem on my login test.

Versions:

Ember: 3.24.0
Ember Data: 3.24.0
jQuery: 3.5.1
Ember Simple Auth: 3.0.1
ember-qunit: 5.1.1
qunit: 2.13.0
qunit-dom: 1.6.0

Here's my `authenticate` action:

```js
authenticate: async function () {
  let { identification, password } = this;

  try {
    await this.session.authenticate('authenticator:devise', identification, password);
  } catch (error) {
    console.error(error);
  }
  
  if (this.session.isAuthenticated) {
    console.log('Authenticated!');
  }
}
```

And my test:

```js
import { module, test } from 'qunit';
import { visit, fillIn, click, currentRouteName } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | login', function(hooks) {
  setupApplicationTest(hooks);

  test('Super User login', async function(assert) {
    await visit('/login');

    assert.equal(currentRouteName(), 'login');

    await fillIn('input[type="email"]', 'xxx@xxx.com');
    await fillIn('input[type="password"]', 'password');
    await click('button[type="submit"]');

    assert.equal(currentRouteName(), 'dashboard');
  });
});
```

Stack trace:

```
Error: Assertion Failed: calling set on destroyed object: <front-end@session:main::ember238>.isAuthenticated = true
    at assert (index.js:172)
    at set (index.js:1524)
    at index.js:2876
    at changeProperties (index.js:647)
    at setProperties (index.js:2870)
    at Proxy.setProperties (observable.js:192)
    at Proxy._setup (internal-session.js:109)
    at internal-session.js:36
    at invokeCallback (rsvp.js:493)
    at publish (rsvp.js:476)
```

**Comment by burritoIand** [comment] 2021-03-17 19:12
hello, I've begun to see the above error on a consistent basis and while working locally with `ember serve`, my app shuts down unexpectedly and I see the error. I'm using fastboot in addition to [ember-simple-auth-token](https://github.com/jpadilla/ember-simple-auth-token/).
```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Assertion Failed: calling set on destroyed object: <ember-foo@session:main::ember402>.isAuthenticated = true".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

**Comment by burritoIand** [comment] 2021-03-17 20:35
update: I think I've got past it by updating a few items in simple auth/simple auth token including getting rid of mixins
