### ISSUE TITLE
{{session.isAuthenticated}} always returns false.

### ISSUE THREAD

**Issue by bdiz** [simplabs/ember-simple-auth#927] opened 2016-03-12 16:54 UTC
{{session.isAuthenticated}} always returns false when used in a component template in ember-simple-auth 1.1.0-beta.1 through 1.1.0-beta.3 starting with commit 6e55271. 

My set up is as follows (component and template): 
```
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),
  actions: {
    invalidateSession() {
      this.get('session').invalidate();
    },
    authenticateSessionWithGoogle() {
      this.get('session').authenticate('authenticator:torii', 'google-oauth2').catch((reason) => {
        alert(reason.error || reason);
        this.set('errorMessage', reason.error || reason);
      }); 
    }   
  }
});
```
```
  {{#if session.isAuthenticated}}
    <a {{action 'invalidateSession'}}>Logout</a>
  {{else}}
    <a {{action 'authenticateSessionWithGoogle'}}>Login with Google</a>
  {{/if}}
```
Even with authentication successful, `session.isAuthenticated` does not evaluate true. The commit before 6e55271, that is 1915445, evaluates to true upon successful authentication.

the dummy app works with 1.0.1-beta.3. Not sure what the dummy app is doing differently from my app...the dummy app does some re-routing which I don't have.

I've created a sample app which recreates the issue: https://github.com/bdiz/ember-simple-auth-bug

Initial bug conversation can be seen here: https://github.com/simplabs/ember-simple-auth/issues/874

**Comment by rmachielse** [comment] 2016-03-14 16:21
@bdiz thanks for the detailed report, I'll investigate asap

**Comment by rmachielse** [comment] 2016-03-16 19:31
@marcoow @bdiz I think I have identified this issue as an issue with the `localStorage` store. Apparently, torii uses `localStorage` as well to temporarily save some data therefore triggering the `storage` event on the window. This caused the local storage store to trigger the `sessionDataUpdated` event, which logged out the session directly after it was logged in.

I have created a fix that only triggers the event if the `storage` event is caused by ember-simple-auth's session key. Can you verify this by using [rmachielse/ember-simple-auth#fix-async_stores](https://github.com/rmachielse/ember-simple-auth/tree/fix-async_stores)?

Alternatively, you can verify wether this issue indeed doesn't occur when you use the cookie store.

**Comment by marcoow** [comment] 2016-03-16 19:33
There was a similar problem with the Cookie store as well BTW: https://github.com/simplabs/ember-simple-auth/commit/df20ac5193e7bdd35eabe6dbb1018349ad1a7b46 - should have told you.

Can you create a [WIP] pull request? I'll try to check that out as soon as I can then.

**Comment by rmachielse** [comment] 2016-03-16 19:35
I see it has been fixed by changing the order of execution there. That could be done here as well but I believe this is cleaner anyway (less interference with other `localStorage` consumers).

**Closed** 2016-04-04 18:40 UTC
