### ISSUE TITLE
Installing ember-cli-simple-auth breaks Ember in mobile Safari

### ISSUE THREAD

**Issue by bravo585** [simplabs/ember-simple-auth#610] opened 2015-08-11 20:52 UTC
For some reason, simply installing ember-cli-simple-auth breaks Ember in Safari (testing on iOS 8.4). Here's a bare-bones example which reproduces the problem:
```
> ember new test-foo
> cd test-foo
> ember generate controller application
```

```
// app/templates/application.hbs
<h2 id="title">Welcome to Ember.js</h2>
<a {{action "foo"}} style="cursor:pointer">CLICK ME {{name}}</a>
{{outlet}}
```

```
// app/controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    foo: function() {
      this.set('name', 'foo');
    }
  }
});
```

If you open this page in Safari on your iPhone, you'll see "foo" when you click "CLICK ME". Now install ember-cli-simple-auth:

```
> ember install ember-cli-simple-auth
```

Reload in Safari, and you'll see clicking "CLICK ME" doesnt do anything.

**Comment by tasn** [comment] 2015-08-25 15:13
Is this related to emberjs/ember.js#5606? Maybe removing the "use strict" will fix it.

**Comment by marcoow** [comment] 2015-08-25 17:09
I think the `"use strict"`s are added by babel to removing them isn't really an option - would be great if someone could track down which exact line is actually causing it.

**Comment by tasn** [comment] 2015-08-25 17:11
See the link I included, this is actually a bug with Webkit on iOS that is triggered by Object.create() and "use strict" (if I remember correctly).

**Comment by marcoow** [comment] 2015-08-25 17:36
@tasn: yes, I saw that but still the bug must be caused by a specific line in ESA. ESA also doesn't use `Object.create` directly anywhere so if it breaks somewhere in Ember itself it needs to be fixed there.

**Comment by marcoow** [comment] 2015-08-25 17:37
You could also check whether [this](https://github.com/rwjblue/broccoli-use-strict-remover) fixes your project.

**Comment by tasn** [comment] 2015-08-25 17:43
I don't have the time to build things from scratch at the moment, but I have removed every occurrence of "use strict" from my vendor.js file, and now everything works as expected, so the use strict bug is definitely the cause.

**Comment by marcoow** [comment] 2015-08-25 17:44
This won't be fixed in ESA as it seems to be a bug in Safari actually and [rwjblue/broccoli-use-strict-remover](https://github.com/rwjblue/broccoli-use-strict-remover) already exists to fix it.

**Closed by marcoow** 2015-08-25 17:44 UTC

**Comment by tasn** [comment] 2015-08-25 17:46
For some reason it doesn't work any more. Odd, as it worked perfectly fine a moment ago.

**Comment by marcoow** [comment] 2015-08-25 17:47
Did you try rwjblue/broccoli-use-strict-remover?

**Comment by tasn** [comment] 2015-08-25 17:55
I'm sorry, but please disregard all of my comments. I haven't realised, but I was testing on the iPhone in incognito mode which has issues with local storage (and apparently triggered other things). After trying in "normal" mode, everything works as expected. I'd wait for OP for more information. Can't reproduce, everything works for me.

Sorry for the noise.
