### ISSUE TITLE
Ember 2.7 and 2.8 seems to be not sending AUTHORIZATION data

### ISSUE THREAD

**Issue by brancusi** [simplabs/ember-simple-auth#1003] opened 2016-06-19 09:35 UTC
Hi,

When upgrading to ember and ember-data 2.7 and 2.8, it seems like the authorization data is not being sent during requests.

Has anyone else experienced this?

Thanks

**Comment by rap-kasta** [comment] 2016-06-20 07:36
Ember _2.7_ + Ember Data _2.6_ works fine, it seems the problem introduced with Ember Data _2.7_

**Comment by marcoow** [comment] 2016-06-20 13:22
This seems to be caused by emberjs/data#3099 and should easily be fixed by (in addition to the current definition of `ajaxOptions`) also overriding `headersForRequest` in `DataAdapterMixin`.

**Comment by JeroenvdV** [comment] 2016-06-23 20:48
Here's a quick workaround for now. Put this in your adapter:

```
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
     headersForRequest() {
        let result = this._super(...arguments);

        const authorizer = this.get('authorizer');

        this.get('session').authorize(authorizer, (headerName, headerValue) => {

            let h = {};
            h[headerName] = headerValue;
            Object.assign(result, h);
        });

        return result;
    }
});
```

**Comment by marcoow** [comment] 2016-06-24 07:47
@JeroenvdV: would you want to prepare a PR, adding that method to the `DataAdapterMixin`?

**Closed** 2016-07-29 16:10 UTC
Labels: bug
