### ISSUE TITLE
Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Token token="

### ISSUE THREAD

**Issue by mojied** [simplabs/ember-simple-auth#527] opened 2015-05-19 01:54 UTC
Hi, everyone 
I provide api by Padrino + Grape, and access by Ember.js,  but got the follow error:

```
Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Token token="OIFTZIizBr/V3/ozvGdeQLMH1rMYzrY2LT8fNND1b74xvjevSSo4tXFnhG51
PDmF0kbl4BrbaRotuBhuoSir2A==
", email="admin@onecoin.im"' is not a valid HTTP header field value.
    at Error (native)
    at Object.send (http://localhost/assets/vendor.js:9859:12)
    at Function.jQuery.extend.ajax (http://localhost/assets/vendor.js:9417:15)
    at http://localhost/assets/vendor.js:69962:19
    at initializePromise (http://localhost/assets/vendor.js:61042:9)
    at new Promise (http://localhost/assets/vendor.js:62670:9)
    at ember$data$lib$system$adapter$$Adapter.extend.ajax (http://localhost/assets/vendor.js:69946:16)
    at ember$data$lib$system$adapter$$Adapter.extend.findQuery (http://localhost/assets/vendor.js:69565:21)
    at ember$data$lib$system$store$finders$$_findQuery (http://localhost/assets/vendor.js:73212:29)
    at ember$data$lib$system$store$$Service.extend.findQuery (http://localhost/assets/vendor.js:78497:68) ember.debug.js:28602
Intermediate-transitioned into 'error' 
```
The config:

```
ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:devise',
    store: 'simple-auth-session-store:cookie'
  };

  ENV['simple-auth-devise'] = {
    serverTokenEndpoint: '/api/v1/sessions/create'
  };

  ENV['simple-auth-cookie-store'] = {
    cookieName: 'im_onecoin'
    //, cookieExpirationTime: 600
  };

if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;

   ENV.contentSecurityPolicy = {
      'default-src': "'none'",
      'script-src': "'self' http://localhost", // Allow scripts from https://cdn.mxpnl.com
      'font-src': "'self' http://localhost data:", // Allow fonts to be loaded from http://fonts.gstatic.com
      'connect-src': "'self' http://localhost http://custom-api.local  data:", // Allow data (ajax/websocket) from api.mixpanel.com and custom-api.local
      'img-src': "'self' https://camo.githubusercontent.com data:",
      'style-src': "'self' 'unsafe-inline' http://localhost", // Allow inline styles and loaded CSS from http://fonts.googleapis.com
      'media-src': "'self' http://localhost data:"
    };
    ENV['simple-auth'].crossOriginWhitelist = ['*'];
  }

 if (environment === 'production') {
    ENV['simple-auth'].crossOriginWhitelist = ['http://onecoin.im'];
  }

```
My versions:

```
DEBUG: ------------------------------- ember.debug.js:3975
DEBUG: Ember                          : 1.10.0 ember.debug.js:3975
DEBUG: Ember Data                     : 1.0.0-beta.16 ember.debug.js:3975
DEBUG: jQuery                         : 1.11.3 ember.debug.js:3975
DEBUG: Ember Simple Auth              : 0.8.0-beta.2 ember.debug.js:3975
DEBUG: Ember Simple Auth Cookie Store : 0.8.0-beta.2 ember.debug.js:3975
DEBUG: Ember Simple Auth Devise       : 0.8.0-beta.2 ember.debug.js:3975
DEBUG: ------------------------------- ember.debug.js:3975
```

The source code:

```
http://github.com/onecoin.im/website.onecoin.im
http://github.com/onecoin.im/api.onecoin.im
```

Anyone know how to resolve it?

**Comment by marcoow** [comment] 2015-05-19 06:41
Which browser are you testing that in? Some browsers don't support setting request headers, see #429

**Comment by mojied** [comment] 2015-05-19 07:50
@marcoow my browser is Chromium whose version 37 or 42, and in the iceweasel, i get the error is 

```
undefined

RSVP.onerrorDefault() vendor.js:39156
__exports__.default.trigger() vendor.js:61674
Promise.prototype._onerror() vendor.js:62686
publishRejection() vendor.js:60917
<匿名> vendor.js:39117
Queue.prototype.invoke() vendor.js:11408
Queue.prototype.flush() vendor.js:11473
DeferredActionQueues.prototype.flush() vendor.js:11278
Backburner.prototype.end() vendor.js:10703
Backburner.prototype.run() vendor.js:10758
run() vendor.js:27192
ember$data$lib$adapters$rest$adapter$$default<.ajax/</hash.error() vendor.js:69959
jQuery.Callbacks/fire() vendor.js:3350
jQuery.Callbacks/self.fireWith() vendor.js:3462
done() vendor.js:9518
.ajax() vendor.js:9421
ember$data$lib$adapters$rest$adapter$$default<.ajax/<() vendor.js:69962
initializePromise() vendor.js:61044
Promise() vendor.js:62670
ember$data$lib$adapters$rest$adapter$$default<.ajax() vendor.js:69963
ember$data$lib$adapters$rest$adapter$$default<.findQuery() vendor.js:69565
ember$data$lib$system$store$finders$$_findQuery() vendor.js:73212
ember$data$lib$system$store$$Store<.findQuery() vendor.js:78497
model() website.js:1255
Route<.deserialize() vendor.js:34469
applyHook() vendor.js:60672
HandlerInfo.prototype.runSharedModelHook() vendor.js:58693
UnresolvedHandlerInfoByParam<.getModel() vendor.js:58919
bind/<() vendor.js:60546
tryCatch() vendor.js:60995
invokeCallback() vendor.js:61007
publish() vendor.js:60978
<匿名> vendor.js:39117
Queue.prototype.invoke() vendor.js:11408
Queue.prototype.flush() vendor.js:11473
DeferredActionQueues.prototype.flush() vendor.js:11278
Backburner.prototype.end() vendor.js:10703
Backburner.prototype.run() vendor.js:10758
Backburner.prototype.join() vendor.js:10777
run.join() vendor.js:27233
__exports__.default<._bubbleEvent() vendor.js:50077
__exports__.default<.setupHandler/<() vendor.js:50028
jQuery.event.dispatch() vendor.js:4872
jQuery.event.add/elemData.handle()
```
I don`t use IE6-9.

**Comment by mojied** [comment] 2015-05-19 08:50
@marcoow Chrome and firefox all can`t use the  setRequestHeader() to set the token? I used them.

**Comment by marcoow** [comment] 2015-05-19 16:48
@mojied: you mean it works with Firefox and Chrome (which it should)?

**Comment by mojied** [comment] 2015-05-20 00:35
@marcoow Yes,  and I find this, 
http://stackoverflow.com/questions/26806899/updated-2-ember-cli-simple-auth-devise-authorization-token-token-user-toke

I think that the 'Token token="abc", email="123@abc.com"' is not a valid HTTP header field value, whether it should be 'Authorization: token="abc", email="123@abc.com"', but i can`t find how to set.

**Comment by tonkonogov** [comment] 2015-05-20 01:42
I can confirm this bug, but for me it happens after upgrade from ember 1.11 to 1.12.
It was totally working on 1.11, without any error or even notices. After upgrade I receive `Failed to execute 'setRequestHeader' on 'XMLHttpRequest'` in the browser console. 
So, it doesn't depend on a browser, since I didn't change it during upgrade.

**Comment by tonkonogov** [comment] 2015-05-20 02:38
I should make an apology. In fact it was my problem - I had entered cyrillic symbols as an email. So the header was actually not valid. For now my headers look like this:

    Accept: "application/json, text/javascript, */*; q=0.01"
    Authorization: "Token token="tcazto54iQvzKyyN3NqG", email="asdiu@asdkjh.asdkjh""

So, I can't confirm the bug and simple-auth works well with ember 1.12. Sorry for confusing.

**Comment by mojied** [comment] 2015-05-20 05:47
@tonkonogov Thank you. You remind me. My  token may be too complicated, I use `token= SecureRandom.hex`, then it works. I think that the browser restrictions on the header`s string.

But, now, I find it logouts when refresh... 
God...

**Comment by mojied** [comment] 2015-05-22 03:51
I have resolved this,  and then find a doc  #204 like it.  I develop the api by using padrino + grape(&rabl), which writes the cookie by using rack.session, so we shuld add 

```
 disable sessions
```

https://github.com/onecoinim/api.onecoin.im/blob/master/config/apps.rb#L3

in the app.rb or in the config/apps, and set the cookieName 'rake.session' like this:

```
  cookieName: 'rack.session'
```

https://github.com/onecoinim/website.onecoin.im/blob/master/config/environment.js#L34

**Comment by mojied** [comment] 2015-05-22 03:56
I want to know if someone have better answer to this, ^=^

**Comment by marcoow** [comment] 2015-06-19 21:09
Closing this - this doesn't seem to be an actual issue with the library.

**Closed by marcoow** 2015-06-19 21:09 UTC
Labels: clarify
