### ISSUE TITLE
Add the ability to make all routes use AuthenticatedRouteMixin by default (except the auth route)

### ISSUE THREAD

**Issue by mdentremont** [simplabs/ember-simple-auth#904] opened 2016-02-19 15:30 UTC
It would be nice if there was an option to automatically make _all_ routes require authentication (except for the authentication route).

This would prevent issues where a dev forgets to add the Authentication mixin. One could then use the UnauthenticationRouteMixin to explicitly not require authentication on certain routes.

**Comment by marcoow** [comment] 2016-02-25 20:53
Would you have sth. in mind how that might look? Maybe you can come up with a PR?

**Comment by mdentremont** [comment] 2016-04-18 18:24
I'll preface by saying the following is a nasty hack, but it demonstrates one way of implementing the desired functionality:

```python
import Ember from 'ember';

import Configuration from 'ember-simple-auth/configuration';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';

export default Ember.Route.reopen({
  session: Ember.inject.service('session'),

  beforeModel(transition) {
    if (Configuration.requireAuthenticateByDefault) {
      if (this.routeName != 'application' && (!UnauthenticatedRouteMixin.detect(this)) &&
          !this.get('session.isAuthenticated')) {
        Ember.assert(
            'The route configured as Configuration.authenticationRoute cannot implement the AuthenticatedRouteMixin mixin as that leads to an infinite transitioning loop!',
            this.get('routeName') !== Configuration.authenticationRoute);

        transition.abort();
        this.set('session.attemptedTransition', transition);
        this.transitionTo(Configuration.authenticationRoute);
        return;
      }
    }
    return this._super(...arguments);
  }
};
```

**Comment by mdentremont** [comment] 2016-04-18 19:39
We might be able to add the following code to the `ApplicationRouteMixin` in order to add the desired functionality:

```
  beforeModel(transition) {
    if (!config['simple-auth'].authenticatedRoutes || this.get('session.isAuthenticated')) {
      return this._super(...arguments);
    }

    if (transition.targetName === Configuration.authenticationRoute) {
      Ember.assert(
          'The route configured as Configuration.authenticationRoute must not implement the AuthenticatedRouteMixin mixin, as that leads to an infinite transitioning loop!',
          !AuthenticatedRouteMixin.detect(this));

      return this._super(...arguments);
    }

    for (let handlerInfo of transition.handlerInfos) {
      if (handlerInfo.name === 'application') {
        // Skip the application route
        continue;
      }

      if (!UnauthenticatedRouteMixin.detect(handlerInfo.handler)) {
        // Allow transition if one of the routes is an unauthenticated route
        this._redirectToAuthenticationRoute(transition);
        return;
      }
    }

    // Only "unauthenticated routes" in the stack, proceed
    return this._super(...arguments);
  },

  _redirectToAuthenticationRoute(transition) {
    transition.abort();
    this.set('session.attemptedTransition', transition);
    this.transitionTo(Configuration.authenticationRoute);
  }
```

**Comment by marcoow** [comment] 2016-04-19 07:07
I think the best solution is probably to just hook into the router DSL as torii does it. As you have to define all routes in `app/router.js` anyway, it's no extra effort to decide whether the route should authenticated or not there. I'm thinking sth. like this:

```js
Router.map(function() {
  this.unauthenticatedRoute('login'); // automatically mixes in the UnauthenticatedRouteMixin
  this.authenticatedRoute('protected'); // automatically mixes in the AuthenticatedRouteMixin
  this.route('about'); // the regular routing method, Ember Simple Auth doesn't change that
});
```

**Comment by ryanlabouve** [comment] 2016-04-19 17:02
Sweet! I'll get a PR for this by end of week.

**Comment by mtangoo** [comment] 2016-04-19 17:33
lovely!

**Comment by mdentremont** [comment] 2016-04-25 14:56
@marcoow: I really like the propose solution!

One thing that does concern me is what happens to auto-generated routers, which are typically not defined in the `router.js`. An example of these would be the `loading` routes.

I suppose one solution would be to explicitly define them in the `router.js`?

**Comment by marcoow** [comment] 2016-04-25 14:58
Hm, the loading routes would be sub routes of the authenticated routes and thus would be authenticated automatically I think as the parent route's `beforeModel` should be executed before they display. Would be sth. that should be verified of course and we should probably have a test for that.

**Comment by mdentremont** [comment] 2016-04-25 15:11
@marcoow Unfortunately the behaviour I'm seeing is that loading routes (when hit directly via the URL in the inspector) do not trigger their parent route's `beforeModel` 😿

**Comment by marcoow** [comment] 2016-04-25 15:13
Hm, ok. We can probably handle that in the router DSL method though.

**Comment by ryanlabouve** [comment] 2016-04-25 15:33
Finishing up tests on my first pass implementation. Will add some for this use case @mdentremont and push up.

**Comment by mike-north** [comment] 2016-04-25 16:31
> Unfortunately the behaviour I'm seeing is that loading routes (when hit directly via the URL in the inspector) do not trigger their parent route's beforeModel 😿

Can you make a small example of this behavior? Remember to call `this._super` in your `beforeModel` route hooks as well

**Comment by mdentremont** [comment] 2016-04-25 17:25
The issue I'm worried about is when hitting the loading route directly (via the URL which is visible in the Ember inspector). It definitely isn't the biggest issue in the world though.

**Comment by marcoow** [comment] 2016-04-25 17:41
Sure, should still behave consistently though.

**Comment by mdentremont** [comment] 2016-04-25 19:31
@marcoow Looks like the loading routes might not be an issue, I think I was just missing a route and was potentially relying on an index route being used.

**Comment by mdentremont** [comment] 2016-04-25 19:41
@marcoow One last edge case: It seems like there is a "routename_loading" route which is generated for each of the root routes (at least in our app), and I can't seem to get those to use the "AuthenticatedRouteMixin" in any way.

**Comment by mike-north** [comment] 2016-04-25 22:15
@mdentremont this is working as intended imo. The `*_loading` route should rely on the authentication check in the `beforeModel` hook from the parent route -- it shouldn't need to do any authentication check on its own.

**Comment by marcoow** [comment] 2016-06-15 15:15
closing this as it will be no longer needed once we have #971

**Closed by marcoow** 2016-06-15 15:15 UTC
Labels: feature
