### ISSUE TITLE
Not redirecting to `routeAfterAuthentication` after logging in

### ISSUE THREAD

**Issue by anthonycollini** [simplabs/ember-simple-auth#1128] opened 2016-12-09 16:55 UTC
Hello,

When I log in for the first time, ember simple auth properly redirects to the route set in the`routeAfterAuthentication` setting. However, if I log out, and then back in, it redirects me to the `index` route, instead of obeying this setting.

Any thoughts as to why this is happening?

**Comment by marcoow** [comment] 2016-12-12 15:40
Can't reproduce this in the dummy app. Can you provide a bit more info:

* ESA version
* your config

**Comment by texpert** [comment] 2016-12-12 15:53
The redirection isn't working with ESA 1.2.0-beta-1 with the same configuration that is working with ESA 1.1.0.

Nothing fancy in config:

```js
/* jshint node: true */

module.exports = function(environment) {
  let ENV = {
    modulePrefix: 'tickets-front',
    environment: environment,
    rootURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false
      }
    },
    contentSecurityPolicy: {
      'connect-src': "*"
    },

    apiHost: 'http://localhost:3000',
    namespace: 'api',

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  ENV['ember-simple-auth'] = {
    routeAfterAuthentication: 'dashboard',
    routeIfAlreadyAuthenticated: 'dashboard'
  };

  if (environment === 'development') {
    ENV.APP.LOG_RESOLVER = true;
    ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_TRANSITIONS = true;
    ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};
```

**Comment by marcoow** [comment] 2016-12-12 15:56
@texpert: can you try moving `routeAfterAuthentication`/`routeIfAlreadyAuthenticated` to the respective routes (see #985)?

**Comment by texpert** [comment] 2016-12-12 19:51
I've tried - put this into the application route:

```js
export default Ember.Route.extend(ApplicationRouteMixin, {
  routeAfterAuthentication: computed(function() {
    return 'dashboard';
  })
});

```

 but it wan't make the transition to 'dashboard'. Also tried to put the same logic into login route - the same negative result.

After making the authentication POST request - there is no other log entry in the console.

**Comment by texpert** [comment] 2016-12-12 19:54
Adding routeIfAlreadyAuthenticated doesn't help either.

**Comment by texpert** [comment] 2016-12-12 21:26
Found that in my case the cause is added into 1.2.0-beta1 response data validation in authenticate method - https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L144

In 1.1.0 the method was just checking if the response status was OK. Now it is also checking the token presence - https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L207

I've put the tokenAttributeName: 'authentication_token' in devide authenticator (that's how the token is defined on my User model)  - and now the redirection's working. 

Strange thing that there is now warning in the console when the token is not found.

Also, I think such a change in the authenticate method would be good to mention in the docs and changelog.

**Comment by marcoow** [comment] 2016-12-13 08:36
The response validation change is mentioned in the changelog actually: https://github.com/simplabs/ember-simple-auth/releases/tag/1.2.0-beta.1 (see third to last item).

Although previously the session might have been authenticated successfully for bad responses it could never have been successfully restored (as the token was actually missing) and there would have been no way to authorize any outgoing requests with the session info (again, as the token was actually missing). Basically the change allows us to catch a few errors early that were previously really hard to find and track down.

@anthonycollini: can you check your server is sending an incorrect response as well maybe?

**Comment by texpert** [comment] 2016-12-13 21:13
@marcoow , when I turned my Rails backend to JSON API format the troubles started again:

- first, the response is wrapped into the 'data' key and it is not normalized yet in the devise authenticator, so this is not working https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L205

- second, I have tried to access the data like this:
```js
const _data = data[resourceName] ? data[resourceName] : data.data.attributes;
```
and it works this way, but further I need the 'authentication_token' attribute, which is dasherized by Ember, thus not being accessible here.

So, could you help, please directing me what's to be done here? Involing the JSONAPIAdapter in some way I have yet to study, or maybe something else?

**Comment by marcoow** [comment] 2016-12-14 08:13
The devise authenticator expects a concrete server response and doesn't work with JSON API (which is probably not the right choice for this kind of thing anyway as it's built for resource-based APIs). In order to support a backend that responds with JSON API you'd have to extend the devise authenticator and convert the response payload so that it looks like what the authenticator expects. You should not try and integrate the authenticator with Ember Data's serializers.

**Comment by texpert** [comment] 2016-12-15 19:03
Made a PR for devise_authenticator to process JSON API responses https://github.com/simplabs/ember-simple-auth/pull/1140

**Comment by knownasilya** [comment] 2016-12-21 18:01
I'm having a similar issue, but it doesn't even go to the index, but stays on the `login` route, but it seems to hit the `index`'s `authenticated-route-mixin`'s `beforeModel` which says it's authenticated..

**Comment by marcoow** [comment] 2016-12-21 18:03
@knownasilya: can you provide some more info (config, version, session state after login, route transition log etc.)?

**Comment by knownasilya** [comment] 2016-12-21 18:10
Session state is good, `isAuthenticated: true` and `data` set.
I'm using v1.1.0 but tried the beta too, same thing.

Here's my config:

```
    'ember-simple-auth': {
      authenticationRoute: 'login',
      routeAfterAuthentication: 'index',
      routeIfAlreadyAuthenticated: 'index',
      authorizer: 'authorizer:token',
      authenticator: 'authenticator:jwt'
    },
```

Here are my transition logs:

```
DEBUG: -------------------------------
ember.debug.js:5734DEBUG: Ember             : 2.10.1
ember.debug.js:5734DEBUG: Ember Data        : 2.10.0
ember.debug.js:5734DEBUG: jQuery            : 3.1.1
ember.debug.js:5734DEBUG: Ember Simple Auth : 1.1.0
ember.debug.js:5734DEBUG: -------------------------------
ember.debug.js:55554 Attempting URL transition to /login
ember.debug.js:26944 Preparing to transition from '' to 'login'
ember.debug.js:55551 Transition #0: application: calling beforeModel hook
ember.debug.js:55551 Transition #0: application: calling deserialize hook
ember.debug.js:55551 Transition #0: application: calling afterModel hook
ember.debug.js:55551 Transition #0: login: calling beforeModel hook
ember.debug.js:55551 Transition #0: login: calling deserialize hook
ember.debug.js:55551 Transition #0: login: calling afterModel hook
ember.debug.js:55551 Transition #0: Resolved all models on destination route; finalizing transition.
ember.debug.js:26873 Transitioned into 'login'
ember.debug.js:55551 Transition #0: TRANSITION COMPLETE.
ember.debug.js:55554 Attempting transition to index
ember.debug.js:26944 Preparing to transition from 'login' to 'index'
ember.debug.js:55554 Attempting transition to index
ember.debug.js:55551 Transition #1: index: calling beforeModel hook
ember.debug.js:55551 Transition #1: index: calling deserialize hook
```

**Comment by marcoow** [comment] 2016-12-21 18:16
Is there any error on the `index` route?

**Comment by knownasilya** [comment] 2016-12-21 18:30
No error, but it seems like it doesn't get past the `model` hook, even though a promise is passed. The promise doesn't trigger `catch` or `then`.. I have RSVP on error setup too, but nothing.

**Comment by marcoow** [comment] 2016-12-21 18:38
if it ever gets to the `model` method it's unlikely that this is an ESA issue though…

**Comment by texpert** [comment] 2016-12-21 18:39
@knownasilya , have you checked ith the currentUser service correctly fetches the userId? I've seen similar behaviour when I was, for example, trying to fetch 'user_id' key's value but the key was named just 'id'.

**Comment by lionelrudaz** [comment] 2017-01-27 06:10
Hi guys,

I believe I've got exactly the same issue that @knownasilya. I tried with ESA 1.1.0, 1.2.0 beta 1 and 2, and get always the same behavior. Basically, whether I do a sign up or a login, the transaction isn't retried with authenticated-route-mixin.

I wonder if it might be because we're both using ember-simple-auth-token...

Here's my repo: https://github.com/lionelrudaz/pro-wellnow-ch

Here's the debug data:

```
DEBUG: -------------------------------
ember.debug.js:5734DEBUG: Ember             : 2.10.2
ember.debug.js:5734DEBUG: Ember Data        : 2.11.0
ember.debug.js:5734DEBUG: jQuery            : 3.1.1
ember.debug.js:5734DEBUG: Ember Simple Auth : 1.2.0-beta.2
ember.debug.js:5734DEBUG: -------------------------------
ember.debug.js:55548 Attempting URL transition to /
ember.debug.js:26944 Preparing to transition from '' to 'index'
ember.debug.js:55545 Transition #0: application: calling beforeModel hook
ember.debug.js:55545 Transition #0: application: calling deserialize hook
ember.debug.js:55545 Transition #0: application: calling afterModel hook
ember.debug.js:55545 Transition #0: index: calling beforeModel hook
ember.debug.js:55545 Transition #0: index: calling deserialize hook
ember.debug.js:55545 Transition #0: index: calling afterModel hook
ember.debug.js:55545 Transition #0: Resolved all models on destination route; finalizing transition.
ember.debug.js:26873 Transitioned into 'index'
ember.debug.js:55545 Transition #0: TRANSITION COMPLETE.
ember.debug.js:55548 Attempting transition to dashboard
ember.debug.js:26944 Preparing to transition from 'index' to 'dashboard'
ember.debug.js:55545 Transition #1: dashboard: calling beforeModel hook
ember.debug.js:55548 Attempting transition to login
ember.debug.js:55545 Transition #1: dashboard: transition was aborted
ember.debug.js:55545 Transition #2: login: calling beforeModel hook
ember.debug.js:55545 Transition #2: login: calling deserialize hook
ember.debug.js:55545 Transition #2: login: calling afterModel hook
ember.debug.js:55545 Transition #1: detected abort.
ember.debug.js:55545 Transition #2: Resolved all models on destination route; finalizing transition.
ember.debug.js:26873 Transitioned into 'login'
ember.debug.js:55545 Transition #2: TRANSITION COMPLETE.
```

When I'm submitting my form, there's basically to transition done. The user is clearly logged in though. isAuthenticated works. And I have access to the protected pages if I click on a link.

attemptedTransition looks correct as well.

Any clue? Let me know if you need more information.

Thanks in advance

**Comment by cloke** [comment] 2017-01-30 15:15
I'm having the same issue, but I also experience it when I logout. It attempts to transition to the login route, but ember aborts the transition because it thinks there is an active transition in process. I am also using ember-simple-auth-token which may be related. I have another project using oauth2 on the same version of ESA and that project is not experiencing the same issue.

<img width="790" alt="screen shot 2017-01-30 at 10 11 57 am" src="https://cloud.githubusercontent.com/assets/15304/22428424/ef44a9e2-e6d4-11e6-863e-a0528529a897.png">

**Comment by marcoow** [comment] 2017-01-30 19:31
I don't know much about ember-simple-auth-token to be honest… Could that be related to #1126 though?

**Comment by marcoow** [comment] 2017-02-08 16:14
Seems like this is an issue with ember-simple-auth-token - closing for now.

**Closed by marcoow** 2017-02-08 16:14 UTC
Labels: triage

**Comment by imsreena7h** [comment] 2018-10-04 09:58
hey @marcoow I also got the same issue of not redirecting to the specified route after authentication
I'm using jwt authentication, 
I'm stuck with this issue for a long time, since it's not showing any kind of errors
Tell me what informations should I provide you for solving this error

**Comment by kikollovet** [comment] 2020-11-05 22:42
I found out a way!!! Hope you all enjoy it a lot!!! Here where I found: https://browntreelabs.com/redirection-in-ember-simple-auth/

to implement it just in the login method that is a promisse put this inside the
.then(() =>{ this.get('session.attemptedTransition').retry()});

Don´t forget that all routes that are just authorized when you are logged in have to have
export default Route.extend(AuthenticatedRouteMixin,{
