### ISSUE TITLE
$.ajaxPrefilter hooking strategy too global?

### ISSUE THREAD

**Issue by jayphelps** [simplabs/ember-simple-auth#270] opened 2014-08-08 00:25 UTC
Since ember-simple-auth uses `$.ajaxPrefilter`, literally *any* calls that end up using `jQuery.ajax` will trigger the prefilter callback and run against any `Authorizer` defined.

This steps on the toes of other libraries and code paths that rely on jQuery's AJAX helpers, as well as makes it impossible to conditionally authorize certain models different ways (or selectively not authorize some).

Any alternatives?

**Comment by ur5us** [comment] 2015-02-22 09:59
@jayphelps with a cookie based approach your session data is send on every request as well so I tend to agree with @marcoow that after being authenticated the auth headers should be send on every request and it shouldn't matter whether it's EmberData or pure jQuery /cc @vladikoff. Moreover, if auth headers break your caching strategy, that's probably app specific, no. Just my 2 cents

**Comment by lfridael** [comment] 2015-07-09 08:39
Tying the library to JQuery feels restrictive.

What about apps that use https://github.com/visionmedia/superagent for Ajax operations? And what about future use cases where JQuery won't be available, such as during a Fastboot page render on the server?

**Comment by marcoow** [comment] 2015-07-09 10:04
Very true, especially with Ember becoming more and more independent of jQuery it would be cool to have a pluggable strategy in ESA. Since that this would most likely be a breaking change this should be done 1.0 though.

Suggestions welcome - I don't really have much time right now as I'm working on getting #522 ready.

**Comment by kimroen** [comment] 2015-07-15 08:34
There's some relevant discussion happening over in [the rfc-proposal for replacing ic-ajax with ember-fetch](https://github.com/ember-cli/rfcs/issues/19) in ember-cli.

**Comment by fsmanuel** [comment] 2015-07-15 10:27
What about adding a public function like [`shouldAuthorizeRequest`](https://github.com/simplabs/ember-simple-auth/blob/6190da91d645f01f6f8b9855720e82284cec8f8a/packages/ember-simple-auth/lib/simple-auth/setup.js#L65) that gives you the context and you can decide if authorization is required or not? The default should be `true` but you can overwrite it.

**Comment by marcoow** [comment] 2015-07-15 11:02
The problem is actually more about how request authorization is triggered at all. Currently the library uses `$.ajaxPrefilter` but when you're e.g. using the `fetch` API that simply doesn't exist so no requests would be authorized at all.

I think the best solution for now is probably to extract the `$.ajaxPrefilter` code into a dedicated initializer that could then be swapped for another one later on when e.g. using `fetch`. I guess the only question is whether that initializer would be loaded automatically (which would require a breaking change to make it optional and swappable later on) or whether users should be forced to manually call it with the 1.0 release.

**Comment by marcoow** [comment] 2015-07-20 19:35
will be fixed in #522

**Comment by jayphelps** [comment] 2015-07-20 19:40
IMO it's odd to close a ticket that is not *yet* fixed.

**Comment by marcoow** [comment] 2015-07-20 19:42
yeah, that's true actually - was a bit over eager cleaning up the tickets…

**Comment by abradner** [comment] 2015-07-21 05:33
I'm joining the party here late, I know, but I had an idea that might interest you:

First, it seems like we're trying to have an ideal solution for two opposing ideas:
1) Have a drop-in, zero config auth toolbelt that just works
2) Have an extensible auth platform that can handle all everything you throw at it.

Having both of these in the core library may well be either impossible or very convoluted, but the Ember team solved a similar problem fairly elegantly: Addons.

Under this model, the Authorization header can be opt-in under the core framework, but with another addon, say ember-simple-auth-automatic, users can get the current behaviour for free. This could be the recommended path for new users or even an enabled default in a vanilla install.

There are a lot of good reasons for having the auth header as opt-in, mostly to do with ajax calls to a third party, eg directly consuming Google's APIs while also using your own OAuth backend.

By being explicit when making a call, you can:
* support interaction with multiple simultaneous OAuth providers in the future with little effort
* ensure that the right tokens get sent to the right places
* ensure you're not accidentally leaking your access tokens to a potentially malicious third party (and this could be a BIG trap).

As for the explicit calls, instances of `$.ajax()` could be trivially replaced with `this.get('session.myAuthProvider').ajax()`
and in true ember/semver form, that could be a feature introduced in the 1.x stream (initially with a feature flag while it's under development) with deprecation warnings when you directly use $.ajax(), then finally extracted into the addon for 2.0, keeping everyone happy.

**Comment by marcoow** [comment] 2015-07-21 06:51
Having the current automatic setup of `$.ajaxPrefilter` in a legacy compatibility addon is a great idea - added to #522.

**Comment by marcoow** [comment] 2015-10-16 13:02
`$.ajaxPrefilter` has been removed in 1.0

**Closed by marcoow** 2015-10-16 13:02 UTC
Labels: question
