### ISSUE TITLE
RSVP.onerrorDefault returns undefined error

### ISSUE THREAD

**Issue by JoshSmith** [simplabs/ember-simple-auth#439] opened 2015-02-16 06:24 UTC
Using `ember-cli-simple-auth` `0.7.3` and `ember` `1.10.0`, I'm seeing the same issue as reported in https://github.com/simplabs/ember-simple-auth/issues/407.

My token endpoint responds with a `401` and the same type of object my server typically responds with.

![screen shot 2015-02-15 at 10 21 42 pm](https://cloud.githubusercontent.com/assets/321667/6207810/0f1701b8-b561-11e4-8137-c65b01cadf3a.png)

This happens in the context of integration tests, and outside that context.

The previous issue said it was fixed, but I am still seeing this and couldn't find, or wasn't sure how to implement, any fix for this.

**Comment by marcoow** [comment] 2015-02-16 09:35
This is probably some rejected promise where the rejection isn't handled anywhere.

**Comment by JoshSmith** [comment] 2015-02-16 16:58
There's a promise in my authenticator that's rejected:

```
CustomAuthenticator = OAuth2.extend
  authenticate: (credentials) ->
    that = this
    new Ember.RSVP.Promise((resolve, reject) ->
      data =
        grant_type: "password"
        username: credentials.identification
        password: credentials.password
        client_id: ENV.OAUTH_CLIENT_ID
      that.makeRequest(that.serverTokenEndpoint, data).then ((response) ->
        Ember.run ->
          expiresAt = that.absolutizeExpirationTime(response.expires_in)
          that.scheduleAccessTokenRefresh response.expires_in, expiresAt, response.refresh_token
          resolve Ember.$.extend(response,
            expires_at: expiresAt,
            access_token: response.access_token,
            user_id: response.user_id
          )
      ), (xhr) ->
        Ember.run ->
          reject xhr.responseJSON or xhr.responseText
      )
```

**Comment by JoshSmith** [comment] 2015-02-16 17:05
I've since tried using just the `simple-auth-authenticator:oauth2-password-grant` authenticator but am seeing the same issue.

**Comment by JoshSmith** [comment] 2015-02-16 17:38
The error goes away when implementing the `Ember.onerror = Ember.K` suggestion as in https://github.com/simplabs/ember-simple-auth/issues/407, but this seems hacky and doesn't fix things in testing mode.

**Comment by marcoow** [comment] 2015-02-16 18:14
Yeah, that's not an appropriate fix. I guess you probably have an unhandled error somewhere else.

**Comment by JoshSmith** [comment] 2015-02-16 18:22
This error was not present until upgrading `ember-cli` and appears only with failed authentication. I've stepped through the app looking for exceptions, and this error happens immediately after the `401`.

**Comment by JoshSmith** [comment] 2015-02-16 18:25
Also, if I insert a breakpoint at:

```
if (Test && Test.adapter) {
  Test.adapter.exception(error);
  Logger.error(error.stack);
}
```

and inspect the `error`, it is the error object provided in my original `reject`: `Object {error: "invalid_resource_owner", error_description: "The provided resource owner credentials are not valid, or resource owner cannot be found", user_id: null}`

**Comment by marcoow** [comment] 2015-02-16 18:26
So this happens when running tests? What does the test look like?

**Comment by JoshSmith** [comment] 2015-02-16 18:28
Yes, it happens in tests, and also happens outside of tests. `Ember.onerror = Ember.K` fixes it outside testing mode.

Here's my test:

```coffeescript
`import { test, moduleFor } from 'ember-qunit'`
`import startApp from '../helpers/start-app'`
`import Ember from 'ember'`
`import { response } from '../helpers/response'`

App = undefined
server = undefined

module "Integration: Login Failure",
  setup: ->
    App = startApp()
    loginResponse =
      error: "invalid_resource_owner"
      error_description: "The provided resource owner credentials are not valid, or resource owner cannot be found"
      user_id: null
    server = new Pretender ->
      @post 'oauth/token/', response(401, loginResponse)

    server.unhandledRequest = (verb, path, request) ->
      console.error "unhandled request", verb, path, request

  teardown: ->
    server.shutdown()
    App.reset()
    Ember.run App, App.destroy

test "Does not log in a user", ->
  expect 3
  visit("/")
  andThen ->
    click(".sign-in-btn")
  andThen ->
    equal $.trim(find(".facebook-btn").text()), "Sign In with Facebook", "The sign in form renders"
    fillIn "#email", "josh@coderly.com"
    fillIn "#password", "password"
    click(".sign-in-btn")
  andThen ->
    equal find(".alert.alert-danger").text(), "Sorry, that password isn't right.", "The error message renders"
    equal find("header .sign-in-btn").text(), "Sign In", "The sign in button renders"
```

All the assertions pass, but the error raises as though it were a failed assertion:

```
{error: invalid_resource_owner, error_description: The provided resource owner credentials are not valid, or resource owner cannot be found, user_id: null}@ 432 ms
Expected: true
Result: false
Diff: true false 
Source: 	
    at http://localhost:4200/assets/test-support.js:4217:13
    at __exports__.default.Adapter.extend.exception (http://localhost:4200/assets/vendor.js:47510:19)
    at RSVP.onerrorDefault (http://localhost:4200/assets/vendor.js:39061:26)
    at Object.__exports__.default.trigger (http://localhost:4200/assets/vendor.js:61587:13)
    at Promise._onerror (http://localhost:4200/assets/vendor.js:62599:16)
    at publishRejection (http://localhost:4200/assets/vendor.js:60830:17)
```

**Comment by JoshSmith** [comment] 2015-02-18 03:40
As mentioned in #407, calling `reject()` without propagating the error seems to "fix" this. I'm not making use of the error outside of my `authenticate` so I don't really need it and needed to move onto other things. But this is definitely a `FIXME` for me.

**Comment by marcoow** [comment] 2015-02-18 07:59
I think if you wrap the error in an actual JS `Error` that should fix it - probably sth. Ember Simple Auth should do well.

```js
reject(new Error(xhr.responseJSON || xhr.responseText));
```

**Comment by JoshSmith** [comment] 2015-02-18 08:07
In that case (and I have to go deeper into that object for an actual message string) the `Error` is still ultimately raised in the same manner as before. Propagating any error of any sort causes this issue.

**Comment by marcoow** [comment] 2015-02-18 08:10
Can you try whether wrapping the rejection in an `Error` fixes it? I'm pretty sure it does because the error you're seeing is probably caused by `onerrorDefault` trying to access the stack of sth. that doesn't have a stack.

**Comment by JoshSmith** [comment] 2015-02-18 08:11
I tried your previous suggestion, or do you mean something different?

**Comment by marcoow** [comment] 2015-02-18 08:12
No, meant that. So where exactly is it failing in `onerrorDefault` then and what's the actual error?

**Comment by JoshSmith** [comment] 2015-02-18 08:14
Here's what I'm seeing:

```
 Error: [object Object]
    at cookacademy-web.js:3475
    at Object.Backburner.run (vendor.js:10667)
    at Object.run (vendor.js:27105)
    at Object.<anonymous> (cookacademy-web.js:3474)
    at Object.<anonymous> (vendor.js:3420)
    at fire (vendor.js:3263)
    at Object.self.fireWith [as rejectWith] (vendor.js:3375)
    at done (vendor.js:9431)
    at Object.callback (vendor.js:9833)
    at Object._readyStateChange (vendor.js:65158)vendor.js:39062 RSVP.onerrorDefault
```

**Comment by JoshSmith** [comment] 2015-02-18 08:15
I similarly see (outside of the context of testing):

```
Error: [object Object]
    at ember-simple-auth.js:32
    at Object.Backburner.run (ember.debug.js:200)
    at Object.run (ember.debug.js:16638)
    at Object.<anonymous> (ember-simple-auth.js:31)
    at Object.<anonymous> (jquery.js:3300)
    at jQuery.Callbacks.fire (jquery.js:3143)
    at Object.jQuery.Callbacks.self.fireWith [as rejectWith] (jquery.js:3255)
    at done (jquery.js:9311)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (jquery.js:9713)
```

**Comment by marcoow** [comment] 2015-02-18 08:16
And `[Object object]` is the error you reject the promise with?

**Comment by JoshSmith** [comment] 2015-02-18 08:18
Yes, precisely.

**Comment by marcoow** [comment] 2015-02-18 08:21
I think you're maybe seeing [this behavior](https://github.com/rwjblue/ember-qunit#async-example) - CoffeeScript has implicit returns doesn't it?

**Comment by JoshSmith** [comment] 2015-02-18 08:24
Yeah, another reason I hate :coffee:

**Comment by marcoow** [comment] 2015-02-18 08:52
So does catching the error fix it?

**Comment by ascudder** [comment] 2015-02-24 08:23
This is also causing problems for me. I'm using the default OAuth2 implementation of the authenticate method, and in the course of upgrading from Ember 1.7.1 to 1.9.1, I realized that my integration tests that checked my login form's error handling started failing because of an error bubbling up from the application code.

I tried wrapping the click event  in my tests that triggers the authenticate action with a try/catch block to catch the exception, it doesn't seem like the catch block ever gets executed. Do you have any other ideas how I might be able to catch the error?

**Comment by marcoow** [comment] 2015-02-24 08:25
@ascudder: you probably need to handle the promise's rejection in you controller or route. Would need some more info to be able to say anything more specific.

**Comment by ascudder** [comment] 2015-02-24 08:45
Ah, ok, now I see where the rejected promise comes from in the session's authenticate method. I had assumed that just using the sessionAuthenticationFailed hook was enough, but I see that it's separate from the promise rejection, so I'll see if I can get something working from that suggestion.

Thanks!

**Comment by JoshSmith** [comment] 2015-02-28 20:21
Doing `reject(new Error(reason))` does not fix this, and I'm not really sure what to do.

@ascudder were you able to get something working here? I think this is the same issue.

**Comment by ascudder** [comment] 2015-02-28 23:21
@JoshSmith I think I have something that might help.

I'm using the `SimpleAuth.LoginControllerMixin` in the controller for my login page. Since the `authenticate` method for the mixin returns the promise from the authenticator's `authenticate` method (whether it's  resolved or rejected), the promise bubbled up as an unhanded error. To handle the failed promise, I added this action handler to my login page's controller:

```CoffeeScript
actions:
   authenticate: ->
       # Catch the failed promise in the SimpleAuth.LoginControllerMixin authenticate action
       @_super().catch( ->
           # empty function to eat the exception
       )
```

After adding this, I my tests passed without using the `Ember.onerror = Ember.K` hack, too. I could also handle the error response from my authenticator right there in the .catch method since it passes the error up from the rejection, but I was already handling the error message in a `sessionAuthenticationFailed` action handler so I left it where it is for now.

I hope that helps!

**Comment by JoshSmith** [comment] 2015-02-28 23:47
@ascudder I have a feeling this is now going to break all of your authentication. When I replace the `authenticate` method with:

```
@_super().catch(Ember.K)
```

this no longer allows me to login normally. I switched back because other parts of `ember-simple-auth` rely on returning a promise that will resolve or reject.

**Comment by JoshSmith** [comment] 2015-03-01 00:10
@marcoow As you said, the error bubbles up because the promise's rejection is never being handled by us as users of `ember-simple-auth`. I had not previously needed to handle this rejection manually; indeed, the first time this happened was 13 days ago when the changing behavior broke previously passing tests. I'm not sure if this because of a change in `Ember`, `Ember.RSVP`, or `ember-simple-auth`.

What this means is that `ember-simple-auth` no longer works out of the box. That is, in every place you call `authenticate`, you must now also `catch` any potential error from a promise rejection, which would happen often in any application that needs to handle authentication errors.

Unless I'm seriously misunderstanding the cause and effect (which is entirely possible), this feels like something that should be addressed at the level of `ember-simple-auth` itself.

**Comment by ascudder** [comment] 2015-03-01 00:19
@JoshSmith My authentication seems to be working fine, still.

Maybe it wasn't clear from my example before, (I edited it to add the controller declaration for a little more context), but I didn't replace any of Simple Auth's authenticate methods with `@_super().catch()` (or, in your case: you shouldn't need to change anything in your CustomAuthenticator class). I added it as an action handler for my login page's controller, so that when the `authenticate` function is handled in my authenticator, the promise that's returned by the authenticator can be caught in my login page controller.

I'm not sure where all of the places in your application are that you're calling `authenticate` from, but it might be possible to handle it in your ApplicationController if you need it catch it across your entire application.

I agree that this caused me a bit of confusion, so maybe this is something the Simple Auth docs or examples could be updated to clarify?

**Comment by JoshSmith** [comment] 2015-03-01 00:23
@ascudder I call `authenticate` in probably six different places across my application for various reasons. One is an authentication with Facebook in a modal dialog, one is regular authentication in a modal, etc. etc. It doesn't make sense to me that I should be separately handling this rejection in all of those cases.

**Comment by marcoow** [comment] 2015-03-02 07:30
I think the problem here is just CoffeeScript's implicit returns. If you add an `authenticate` action handler that does

```coffee
@_super()
return false
```

instead of

```coffee
@_super().catch(Ember.K)
```

that probably works as well.

**Comment by michaeldeitcher** [comment] 2015-03-03 18:02
@JoshSmith If you need the behavior to work in more than one controller, you could create your own mixin that handles this behavior.

```
MyLoginControllerMixin = Ember.Mixin.create(LoginControllerMixin,
  actions:
    authenticate: ->
      # Catch the failed promise in the SimpleAuth.LoginControllerMixin authenticate action
      @_super().catch( ->
        # empty function to eat the exception
      )
      false
)
```

**Comment by marcoow** [comment] 2015-03-05 09:31
[This line](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/authentication-controller-mixin.js#L40) should probably be changed to not return the promise anymore, although that's a breaking change and makes customizing the behavior a little harder.

**Comment by treyhunner** [comment] 2015-03-07 02:52
This is also causing me grief by breaking my login failure tests.  I think this should be relabeled as "bug".

Anything I can do to expedite a fix for this?  I'm happy to help test or provide code demonstrating this failure if needed.

**Comment by marcoow** [comment] 2015-03-07 07:29
@treyhunner: Like I said above - I think it would be best to not return the promise from the `AuthenticationControllerMixin` and `LoginControllerMixin` anymore. Feel free to submit a PR.

**Comment by marcoow** [comment] 2015-03-17 20:25
I'm probably going to deprecate `LoginControllerMixin` and `AuthenticationControllerMixin` in the next release. There's just very little functionality in there that doesn't really justify the effort of maintaining the mixins. Also removing them would make the whole library a little less "automagic" as the developer needs to interact with the session directly which also is simple enough to make everyone do that.

**Comment by marcoow** [comment] 2015-03-18 20:53
`LoginControllerMixin` and `AuthenticationControllerMixin` are now deprecated in favor of everybody implementing their own `authenticate` and `invalidate` actions in the routes, controllers or components they need them. Also catching rejecting promises is up to each developer then.

**Closed by marcoow** 2015-03-18 20:53 UTC
Labels: clarify

**Comment by gzurbach** [comment] 2015-04-03 06:24
I might be missing something but I'm having the same issue and I'm not able to catch the promise rejection errors before they get send to the RSVP global error handler. Note that I never used `LoginControllerMixin` or `AuthenticationControllerMixin`. 

Here is my login controller:
```javascript
actions: {
    login: function () {
        var auth = self.get('session').authenticate('authenticator:passport', {
            username: this.get('username'),
            password: this.get('password')
        });
        auth.then(function () {
            alertify.success("User authenticated.");
        });
        auth.catch(function () {
            alertify.error("Cannot authenticate.");
        });
    }
}
```
And here is my custom authenticator:
```javascript
authenticate: function(options) {
    return new Ember.RSVP.Promise(function(resolve, reject) {
        var post = Ember.$.ajax({
            type: 'POST',
            url: url,
            data: {
                username: options.username,
                password: options.password
            }
        });
        post.done(function (data) {
            resolve({ userId: data.user.id });
        });
        post.fail(function (err) {
            reject(err);
        });
    });
},
```
I would expect that code to catch all promise rejections. Yet, my `RSVP.on('error')` handler is being called (twice!) each time a user fails to authenticate. Am I missing something? I am running 0.7.2.

Thanks!

**Comment by marcoow** [comment] 2015-04-05 08:06
Which rejected promise is actually passed to the `onerror` handler? Also are there any error arguments?

**Comment by gzurbach** [comment] 2015-04-05 22:15
Thanks for your answer! The `onerror` handler receives an `Object` containing the following:
```
{
  responseText: "Unauthorized"
  status: 401
  [...]
}
```
I setup breakpoints all over and the `onerror` handler is called right after:
```javascript
auth.catch(function () {
    alertify.error("Cannot authenticate.");
});
```
It doesn't make any sense. If I `catch` the rejection locally then it should not bubble up like that.

**Comment by marcoow** [comment] 2015-04-06 07:56
I guess that's more a general RSVP question. Also I'd write the above as

```js
actions: {
    login: function () {
        var auth = this.get('session').authenticate('authenticator:passport', {
            username: this.get('username'),
            password: this.get('password')
        }).then(function () {
            alertify.success("User authenticated.");
        }, function () {
            alertify.error("Cannot authenticate.");
        });
    }
}
```

**Comment by dweebit** [comment] 2015-08-05 16:32
I had a similar problem to @gzurbach's, and rewriting the code to use then, rather than catch (like @marcoow has in their above comment) fixed it. ARRGGG!!! (thanks)

**Comment by gzurbach** [comment] 2015-08-05 16:43
Good to know. There are actually a couple subtle differences between using the second argument of `then` vs using `catch`. But my conclusion after reading on that matter was that using `catch` is actually better because `catch` will also catch errors from the `then` statement.

I guess I'm missing something here and gonna have to read more about it.
